-- AlterTable
ALTER TABLE "Flight" ADD COLUMN IF NOT EXISTS "availableSeats" INTEGER,
ADD COLUMN IF NOT EXISTS "arrivalLoadFactor" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "departureLoadFactor" DOUBLE PRECISION;
